### ISSUE TITLE
Exclude *kdump.img files from reboot hygiene policy check

### ISSUE THREAD

**Issue by swapdisk** [oamg/leapp-supplements#3]
@Wecros, I just ran a test and observed that /boot/initramfs-3.10.0-1160.90.1.el7.x86_64kdump.img was flagged by the "Modified files under /boot detected" check. Of course, this can be expected because kdumpctl builds this image at boot time if no kdump initial ramdisk found.

What do you think about updating the check to ignore files matching *kdump.img?

**Comment by Wecros** [comment]
Sure, sounds like a good exclusion for such use cases.

**Comment by Wecros** [comment]
Should be resolved by https://github.com/oamg/leapp-supplements/pull/4

**Comment by swapdisk** [comment]
PR merged. Thanks!
